data_process:
  ros__parameters:
    laser:
      vertical_scans: 32
      horizontal_scans: 1080
      ang_bottom: -10.6
      ang_top: 30.7
      sensor_mount_angle: 0.0
      ground_scan_index: 20
    projection:
      segment_theta: 60
      segment_valid_point_num: 5
      segment_valid_line_num: 3